// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.1
// source: app/config/pb/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty" binding:"required"`
	ConfigmapName string `protobuf:"bytes,2,opt,name=configmap_name,json=configmapName,proto3" json:"configmap_name,omitempty" binding:"required"`
}

func (x *SyncConfigRequest) Reset() {
	*x = SyncConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_config_pb_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigRequest) ProtoMessage() {}

func (x *SyncConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_pb_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigRequest.ProtoReflect.Descriptor instead.
func (*SyncConfigRequest) Descriptor() ([]byte, []int) {
	return file_app_config_pb_config_proto_rawDescGZIP(), []int{0}
}

func (x *SyncConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SyncConfigRequest) GetConfigmapName() string {
	if x != nil {
		return x.ConfigmapName
	}
	return ""
}

type SyncConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SyncConfigResponse) Reset() {
	*x = SyncConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_config_pb_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigResponse) ProtoMessage() {}

func (x *SyncConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_pb_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigResponse.ProtoReflect.Descriptor instead.
func (*SyncConfigResponse) Descriptor() ([]byte, []int) {
	return file_app_config_pb_config_proto_rawDescGZIP(), []int{1}
}

func (x *SyncConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_app_config_pb_config_proto protoreflect.FileDescriptor

var file_app_config_pb_config_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x70, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x62, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0x58, 0x0a, 0x11, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x6d, 0x61, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2e,
	0x0a, 0x12, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x58,
	0x0a, 0x11, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x2e, 0x62, 0x73, 0x67, 0x63, 0x68, 0x69, 0x6e, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x75, 0x70, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2d, 0x77, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_config_pb_config_proto_rawDescOnce sync.Once
	file_app_config_pb_config_proto_rawDescData = file_app_config_pb_config_proto_rawDesc
)

func file_app_config_pb_config_proto_rawDescGZIP() []byte {
	file_app_config_pb_config_proto_rawDescOnce.Do(func() {
		file_app_config_pb_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_config_pb_config_proto_rawDescData)
	})
	return file_app_config_pb_config_proto_rawDescData
}

var file_app_config_pb_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_config_pb_config_proto_goTypes = []interface{}{
	(*SyncConfigRequest)(nil),  // 0: config.SyncConfigRequest
	(*SyncConfigResponse)(nil), // 1: config.SyncConfigResponse
}
var file_app_config_pb_config_proto_depIdxs = []int32{
	0, // 0: config.SyncConfigService.SyncConfig:input_type -> config.SyncConfigRequest
	1, // 1: config.SyncConfigService.SyncConfig:output_type -> config.SyncConfigResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_config_pb_config_proto_init() }
func file_app_config_pb_config_proto_init() {
	if File_app_config_pb_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_config_pb_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_config_pb_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_config_pb_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_config_pb_config_proto_goTypes,
		DependencyIndexes: file_app_config_pb_config_proto_depIdxs,
		MessageInfos:      file_app_config_pb_config_proto_msgTypes,
	}.Build()
	File_app_config_pb_config_proto = out.File
	file_app_config_pb_config_proto_rawDesc = nil
	file_app_config_pb_config_proto_goTypes = nil
	file_app_config_pb_config_proto_depIdxs = nil
}
